mvc_app/Models/Shop.cs
using System.Collections.Generic;

namespace mvc_app.Models
{
    //класс цеха
    public class Shop
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int? DepartmentId { get; set; }
        public Department Department { get; set; }
        public List<User> Users {get; set;} = new List<User>();
    }
}

mvc_app/Controllers/ShopsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using mvc_app.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartBreadcrumbs.Attributes;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace mvc_app.Controllers
{
    [Authorize]
    public class ShopsController : Controller
    {
        private ApplicationContext db;
        private readonly ILogger _logger;

        public ShopsController(ApplicationContext context, ILogger<AdminController> logger)
        {
            db = context;
            _logger = logger;
        }
        /// <summary>
        /// Перенаправляет на нужную форму в зависимости от цеха
        /// </summary>
        /// <param name="id"></param>
        /// <param name="dataEntered"></param>
        /// <returns></returns>

        [Route("Shops/Edit")]
        [Breadcrumb("Цех", FromAction="Index", FromController=typeof(HomeController))]
        public async Task<IActionResult> Index(int? id)
        {   
            User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            Role role = await db.Roles.FirstOrDefaultAsync(p => p.Id == user.RoleId);
            ViewBag.Role = role.Name;
            if (id != null)
            {
                int Id = id.GetValueOrDefault();
                var shopActions = new List<string> {"Shop101", "Shop102","Shop104","Shop105","Shop106_1","Shop106_2","Shop201","Shop204","Shop401","Shop402"};
                return View(shopActions[Id-1]);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Shop101(Data101 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 1;
            data.Calculate();
            db.data101.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=1});
        }

        [HttpPost]
        public async Task<IActionResult> Shop102(Data102 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 2;
            data.Calculate();
            db.data102.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=2});
        }

        [HttpPost]
        public async Task<IActionResult> Shop104(Data104 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 3;
            data.Calculate();
            db.data104.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=3});
        }

        [HttpPost]
        public async Task<IActionResult> Shop105(Data105 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 4;
            data.Calculate();
            db.data105.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=4});
        }

        [HttpPost]
        public async Task<IActionResult> Shop106_1(Data106_1 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 5;
            data.Calculate();
            db.data106_1.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=5});
        }

        [HttpPost]
        public async Task<IActionResult> Shop106_2(Data106_2 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 6;
            data.Calculate();
            db.data106_2.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=6});
        }

        [HttpPost]
        public async Task<IActionResult> Shop201(Data201 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            // data.ShopId = 7;
            // data.Calculate();
            // db.data201.Add(data);
            // await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=7});
        }

        [HttpPost]
        public async Task<IActionResult> Shop204(Data204 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 8;
            data.Calculate();
            db.data204.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=8});
        }

        [HttpPost]
        public async Task<IActionResult> Shop401(Data401 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 9;
            data.Calculate();
            db.data401.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=9});
        }

        [HttpPost]
        public async Task<IActionResult> Shop402(Data402 data)
        {
            // User user = await db.Users.FirstOrDefaultAsync(p => p.Number == User.Identity.Name);
            data.ShopId = 10;
            data.Calculate();
            db.data402.Add(data);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new {id=10});
        }

        public async Task<IActionResult> ShopHistory(int? id, int? pageNumber)
        {
            var data = from s in db.data101 select s;
            int pageSize = 1;
            return View(await PaginatedList<Data101>.CreateAsync(data, pageNumber ?? 1, pageSize));
        }

        public ViewResult Test()
        {
            Data102 data = new Data102{};
            return View(data);
        }
    }
}

mvc_app/Views/Shops/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

mvc_app/Views/Shops/Shop101.cshtml
@model mvc_app.Models.Data101
@{
    ViewBag.Title = "Ц.101 ввод";
}
<p>Ввод данных</p>
<form asp-action="Shop101" asp-controller="Shops">
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Сырье</th>
                <th></th>
                <th>Норма <a href="#">Изменить</a> </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Ethylene)</b></td>
                <td><input type="text" asp-for="Ethylene" class="form-control form-control-sm" /></td>
                <td></td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Propylene)</b></td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Propylene"></td>
                <td></td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.BenzinLight)</b></td>
                <td><input type="text" asp-for="BenzinLight" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.BenzinHard)</b></td>
                <td><input type="text" asp-for="BenzinHard" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Reflux)</b></td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Reflux"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Butan)</b></td>
                <td><input type="text" asp-for="Butan" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <!-- Остальные поля рассчитываются -->
            @* <tr>
                <td>@Html.DisplayNameFor(model=>model.Kerosin)</td>
                <td><input type="text" asp-for="Kerosin" class="form-control form-control-sm" disabled/></td>
                <td>0.00095</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Natrium)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Natrium"></td>
                <td>0.00194</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Metanol)</td>
                <td><input type="text" asp-for="Metanol" class="form-control form-control-sm" /></td>
                <td>0.000234</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Agidol)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Agidol"></td>
                <td>0.0004</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Ingibitor)</td>
                <td><input type="text" asp-for="Ingibitor" class="form-control form-control-sm" /></td>
                <td>0.000257</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.FractionC4)</td>
                <td><input type="text" asp-for="FractionC4" class="form-control form-control-sm" /></td>
                <td>0.24039</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.FractionPropan)</td>
                <td><input type="text" asp-for="Butan" class="form-control form-control-sm" /></td>
                <td>0.055335</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.FractionPyrolize)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="FractionPyrolize "></td>
                <td>0.4928</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.SPT)</td>
                <td><input type="text" asp-for="SPT" class="form-control form-control-sm" /></td>
                <td>0.122576</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.MVF)</td>
                <td><input type="text" asp-for="MVF" class="form-control form-control-sm" /></td>
                <td>0.444772</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Waste)</td>
                <td><input type="text" asp-for="Waste" class="form-control form-control-sm" /></td>
                <td>0.02</td>
            </tr> *@
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-light" />
    </div>
</form>

mvc_app/Views/Shops/Shop102.cshtml
@model mvc_app.Models.Data102
@{
    ViewBag.Title = "Ц.102 ввод";
}
<p>Ввод данных</p>
<form asp-action="Shop102" asp-controller="Shops">
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Сырье</th>
                <th></th>
                <th>Норма</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.PolyethyleneS1)</b></td>
                <td><input type="text" asp-for="PolyethyleneS1" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            @* <tr>
                <td>@Html.DisplayNameFor(model=>model.Ethylene1)</td>
                <td><input type="text" asp-for="Ethylene1" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.InitDTBP)</td>
                <td><input type="text" asp-for="InitDTBP" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.InitBU50AL)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="InitBU50AL"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.InitTBPEH)</td>
                <td><input type="text" asp-for="InitTBPEH" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.InitOil)</td>
                <td><input type="text" asp-for="InitOil" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Trigonox)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Trigonox"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyethyleneNM)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PolyethyleneNM"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA3)</td>
                <td><input type="text" asp-for="PolyWasteA3" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA2)</td>
                <td><input type="text" asp-for="PolyWasteA2" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteB)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PolyWasteB"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA4)</td>
                <td><input type="text" asp-for="PolyWasteA4" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
        </tbody> *@
    </table>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-light" />
    </div>
</form>

mvc_app/Views/Shops/Shop104.cshtml
@model mvc_app.Models.Data104
@{
    ViewBag.Title = "Ц.104 ввод";
}
<p>Ввод данных</p>
<form asp-action="Shop104" asp-controller="Shops">
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Сырье</th>
                <th></th>
                <th>Норма</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Ethylene)</b></td>
                <td><input type="text" asp-for="Ethylene" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Propylene)</b></td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Propylene"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.BenzinLight)</b></td>
                <td><input type="text" asp-for="BenzinLight" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.BenzinHard)</b></td>
                <td><input type="text" asp-for="BenzinHard" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Reflux)</b></td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Reflux"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Butan)</b></td>
                <td><input type="text" asp-for="Butan" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            @* <tr>
                <td>@Html.DisplayNameFor(model=>model.Kerosin)</td>
                <td><input type="text" asp-for="Kerosin" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Natrium)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Natrium"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Metanol)</td>
                <td><input type="text" asp-for="Metanol" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Agidol)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Agidol"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Ingibitor)</td>
                <td><input type="text" asp-for="Ingibitor" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.DimetilSulfid)</td>
                <td><input type="text" asp-for="DimetilSulfid" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.FractionC4)</td>
                <td><input type="text" asp-for="FractionC4" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.FractionPropan)</td>
                <td><input type="text" asp-for="Butan" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.FractionPyrolize)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="FractionPyrolize "></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.SPT)</td>
                <td><input type="text" asp-for="SPT" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.MVF)</td>
                <td><input type="text" asp-for="MVF" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Waste)</td>
                <td><input type="text" asp-for="Waste" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr> *@
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-light" />
    </div>
</form>

mvc_app/Views/Shops/Shop105.cshtml
@model mvc_app.Models.Data105
@{
    ViewBag.Title = "Ц.105 ввод";
}
<p>Ввод данных</p>
<form asp-action="Shop105" asp-controller="Shops">
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Сырье</th>
                <th></th>
                <th>Норма</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.PolyethyleneS2)</b></td>
                <td><input type="text" asp-for="PolyethyleneS2" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            @* <tr>
                <td>@Html.DisplayNameFor(model=>model.Ethylene1)</td>
                <td><input type="text" asp-for="Ethylene1" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Ethylene2)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Ethylene2"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.InitDTBP)</td>
                <td><input type="text" asp-for="InitDTBP" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.InitTBPEH)</td>
                <td><input type="text" asp-for="InitTBPEH" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.InitOil)</td>
                <td><input type="text" asp-for="InitOil" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Oxygen)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Oxygen"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.Propan)</td>
                <td><input type="text" asp-for="Propan" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyethyleneNM)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PolyethyleneNM"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA2)</td>
                <td><input type="text" asp-for="PolyWasteA2" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteB)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PolyWasteB"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA4)</td>
                <td><input type="text" asp-for="PolyWasteA4" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr> *@
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-light" />
    </div>
</form>

mvc_app/Views/Shops/Shop106_1.cshtml
@model mvc_app.Models.Data106_1
@{
    ViewBag.Title = "Ц.106-1 ввод";
}
<p>Ввод данных</p>
<form asp-action="Shop106_1" asp-controller="Shops">
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Сырье</th>
                <th></th>
                <th>Норма</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Polyethylene1)</b></td>
                <td><input type="text" asp-for="Polyethylene1" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.PlenkaPoly)</b></td>
                <td><input type="text" asp-for="PlenkaPoly" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.BagPoly)</b></td>
                <td><input type="text" asp-for="BagPoly" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            @* <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyethyleneS1)</td>
                <td><input type="text" asp-for="PolyethyleneS1" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.BagPolyprop)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="BagPolyprop"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA2)</td>
                <td><input type="text" asp-for="PolyWasteA2" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteB)</td>
                <td><input type="text" asp-for="PolyWasteB" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA4)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PolyWasteA4"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteD)</td>
                <td><input type="text" asp-for="PolyWasteD" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PlenkaWaste)</td>
                <td><input type="text" asp-for="PlenkaWaste" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PlenkaWasteE2)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PlenkaWasteE2"></td>
                <td>0.00072</td>
            </tr> *@
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-light" />
    </div>
</form>

mvc_app/Views/Shops/Shop106_2.cshtml
@model mvc_app.Models.Data106_2
@{
    ViewBag.Title = "Ц.106-2 ввод";
}
<p>Ввод данных</p>
<form asp-action="Shop106_2" asp-controller="Shops">
    <table class="table table-sm">
        <thead>
            <tr>
                <th>Сырье</th>
                <th></th>
                <th>Норма</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>@Html.DisplayNameFor(model=>model.Polyethylene2)</b></td>
                <td><input class="form-control form-control-sm" id="role" asp-for="Polyethylene2"></td>
                <td>0.00072</td>
            <tr>
                @* <td>@Html.DisplayNameFor(model=>model.PolyethyleneS2)</td>
                <td><input type="text" asp-for="PolyethyleneS2" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA2)</td>
                <td><input type="text" asp-for="PolyWasteA2" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteB)</td>
                <td><input type="text" asp-for="PolyWasteB" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteA4)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PolyWasteA4"></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PolyWasteD)</td>
                <td><input type="text" asp-for="PolyWasteD" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PlenkaWaste)</td>
                <td><input type="text" asp-for="PlenkaWaste" class="form-control form-control-sm" /></td>
                <td>0.00072</td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model=>model.PlenkaWasteE2)</td>
                <td><input class="form-control form-control-sm" id="role" asp-for="PlenkaWasteE2"></td>
                <td>0.00072</td>
            </tr> *@
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-light" />
    </div>
</form>